version: '3.0'
services:
  database:
    build: .docker/mysql
    environment:
      MYSQL_DATABASE: altaliza
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./DbInitialScripts:/docker-entrypoint-initdb.d
    restart: always
    
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database
